name: Build and Deploy server

on:
  push:
    branches:
      - main
      
jobs:
  # Check code quality and basic syntax
  check-code:
    name: Check Code Quality
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check Python syntax (compile all files)
        run: |
          python -m compileall .
  
              
  # Build and push Docker image to GitHub Container Registry
  build-docker:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: check-code                    # Runs only if Job 1 passes
    if: github.event_name == 'push'
    permissions:
      contents: read
      packages: write
    steps:
      - name: Get the code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}:latest .
          docker push ghcr.io/${{ github.repository }}:latest
          
  # Deploy to EC2 via SSH
  deploy:
    runs-on: ubuntu-latest
    needs: build-docker

    steps:
      - name: Deploy to EC2 via SSH (Docker)
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}

            docker pull ghcr.io/${{ github.repository }}:latest

            docker stop fastapi || true
            docker rm fastapi || true

            docker run -d \
              --name fastapi \
              -p 8000:8000 \
              -e DB_HOST=${{ secrets.DB_HOST }} \
              -e DB_USER=${{ secrets.DB_USER }} \
              -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
              -e DB_NAME=${{ secrets.DB_NAME }} \
              -e DB_PORT=${{ secrets.DB_PORT }} \
              ghcr.io/${{ github.repository }}:latest